version: "3.9"  # Versão do Docker Compose

services:
  postgres:
    image: postgres:15
    container_name: meu-banco-postgres
    restart: always 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: meu_banco  # Nome do banco de dados
    ports:
      - "5432:5432"  # Mapeia a porta 5432 do container para a porta 5432 do host
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # Persiste os dados do banco em um volume